### ISSUE TITLE
Transfer to Jazzband

### ISSUE THREAD

**Issue by camilonova** [jazzband/django-admin-sortable#249]
Looking at https://github.com/alsoicode/django-admin-sortable/commit/b56ded8f0fab6a2790e52185e1b88ff78aad80bb

Would you consider moving this project to Jazzband?

You can start the process here: https://jazzband.co/about/guidelines

**Comment by alsoicode** [comment]
What do I use for the organization name to transfer to? I tried "Jazzband", however the transfer button is still disabled.

**Comment by camilonova** [comment]
maybe all lowercase? https://github.com/jazzband/

**Comment by andylolz** [comment]
> I tried "Jazzband", however the transfer button is still disabled

I think the button remains disabled until the second input is correctly populated.

The second input needs to contain:
```
alsoicode/django-admin-sortable
```

**Comment by alsoicode** [comment]
I'm getting this error: You don’t have the permission to create public repositories on jazzband

**Comment by andylolz** [comment]
Oh, I see – Perhaps you first need to click “login to join” here: https://jazzband.co
